# Generated by Django 4.1.7 on 2023-03-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizador',
            options={'verbose_name_plural': 'Organizadores'},
        ),
        migrations.AddField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(default=2),
            preserve_default=False,
        ),
    ]
