# Generated by Django 4.1.7 on 2023-05-15 12:25

from django.db import migrations, models
import ingressos.models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=ingressos.models.upload_image_evento),
        ),
    ]
