# Generated by Django 4.1.7 on 2023-03-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0002_alter_categoria_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
