# Generated by Django 4.1.7 on 2023-03-02 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0002_alter_organizador_options_evento_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompraIngresso',
            new_name='Compra',
        ),
    ]
