# Generated by Django 4.1.7 on 2023-03-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0003_evento_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(upload_to='media/evento/'),
        ),
    ]
