# Generated by Django 4.1.3 on 2023-03-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0004_alter_evento_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='vendidos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/evento/'),
        ),
    ]
