# Generated by Django 4.1.7 on 2023-03-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0004_alter_evento_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/evento/'),
        ),
    ]
